# Generated by Django 6.0.6 on 2026-06-26 21:48

from django.db import migrations, models


def migrate_tokenizing_status(apps, schema_editor):
    Property = apps.get_model('properties', 'Property')
    Property.objects.filter(status='tokenizing').update(status='tokenization_pending')


def reverse_tokenizing_status(apps, schema_editor):
    Property = apps.get_model('properties', 'Property')
    Property.objects.filter(status='tokenization_pending').update(status='tokenizing')


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_tokenization_operation_timestamps'),
    ]

    operations = [
        migrations.RunPython(migrate_tokenizing_status, reverse_tokenizing_status),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('documents_uploaded', 'Documents Uploaded'), ('ready_for_review', 'Ready for Review'), ('ready_for_tokenization', 'Ready for Tokenization'), ('tokenization_pending', 'Tokenization Pending'), ('tokenized', 'Tokenized'), ('active', 'Active'), ('suspended', 'Suspended'), ('archived', 'Archived')], default='draft', max_length=32),
        ),
    ]
